platform :ios, '7.0'
post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['VALID_ARCHS'] = 'armv7 armv7s'
      config.build_settings['ARCHS'] = 'armv7 armv7s'
    end
  end
end

pod 'SDWebImage'
pod 'Masonry', '~> 0.4.0'
pod 'NSTimer-Blocks', '~> 0.0.1'
pod 'LVUtils', '~> 0.0.1'
